# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- checkout: self
  persistCredentials: true
  clean: true

- powershell: |
   git --version
   Write-Host "setup author info"
   git config user.email jie.lu@outlook.com
   git config user.name "Jie Lu"
  displayName: 'Set git user'

- script: |
    npm install -g @angular/cli
    npm install
    npm version patch
    ng build --prod
  displayName: 'npm install and build'

- powershell: |
   git --version
   Write-Host "setup author info"
   git config user.email jie.lu@outlook.com
   git config user.name "Jie Lu"
   Write-Host "git commit with message"
   git commit -a -m "Test Commit from Azure DevOps"
   Write-Host "git push"
   git push
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/docs'
    Contents: |
      **
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
